### ISSUE TITLE
struct.error: ubyte format requires 0 <= number <= 255

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-grafana#19]
```
Jan 11 12:10:14 igel aiohttp.server[33073]: Error handling request
                                            Traceback (most recent call last):
                                              File "/home/service/envs/grafana/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
                                                resp = await task
                                              File "/home/service/envs/grafana/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
                                                resp = await handler(request)
                                              File "/home/service/metricq-grafana/metricq_grafana/views.py", line 25, in query
                                                resp = await get_history_data(request.app, req_json)
                                              File "/home/service/metricq-grafana/metricq_grafana/amqp.py", line 40, in get_history_data
                                                for target in targets
                                              File "/home/service/metricq-grafana/metricq_grafana/target.py", line 48, in get_response
                                                self._get_data(app, start_time, end_time, interval), self._get_metadata(app)
                                              File "/home/service/metricq-grafana/metricq_grafana/target.py", line 81, in _get_data
                                                request_type=HistoryRequestType.FLEX_TIMELINE,
                                              File "/home/service/envs/grafana/lib/python3.7/site-packages/metricq/history_client.py", line 279, in history_data_request
                                                await self.history_exchange.publish(msg, metric)
                                              File "/home/service/envs/grafana/lib/python3.7/site-packages/aio_pika/exchange.py", line 242, in publish
                                                timeout=timeout,
                                              File "/home/service/envs/grafana/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
                                                return await fut
                                              File "/home/service/envs/grafana/lib/python3.7/site-packages/aiormq/channel.py", line 471, in basic_publish
                                                self.writer.write(pamqp.frame.marshal(frame, self.number))
                                              File "/home/service/envs/grafana/lib/python3.7/site-packages/pamqp/frame.py", line 93, in marshal
                                                return _marshal_method_frame(frame_value, channel_id)
                                              File "/home/service/envs/grafana/lib/python3.7/site-packages/pamqp/frame.py", line 241, in _marshal_method_frame
                                                struct.pack('>I', frame_value.index) + frame_value.marshal())
                                              File "/home/service/envs/grafana/lib/python3.7/site-packages/pamqp/specification.py", line 188, in marshal
                                                output.append(encode.by_type(data_value, data_type))
                                              File "/home/service/envs/grafana/lib/python3.7/site-packages/pamqp/encode.py", line 453, in by_type
                                                return short_string(value)
                                              File "/home/service/envs/grafana/lib/python3.7/site-packages/pamqp/encode.py", line 245, in short_string
                                                return struct.pack('B', len(value)) + value
                                            struct.error: ubyte format requires 0 <= number <= 255

```

What's going on here? Something too long maybe?

**Comment by phijor** [comment]
This might be a "Short String" that is too long, similar to [this](https://stackoverflow.com/questions/20393402/short-string-too-long-exception). Do we have metric names that are longer than 255 bytes? AMQP 0.9.1 requires the routing key to be a [short string](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.publish.routing-key).

**Comment by phijor** [comment]
I think this was fixed in https://github.com/metricq/metricq-python/pull/63.

Since 93063b9de261f6670cadf67c26fcce4582254e9e we depend on `metricq` 2.0, which includes the above fix.
