### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'int' and 'Timedelta'

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-grafana#25]
It's broken

```
Mai 05 11:27:57 metricq metricq-grafana[118045]: 2021-05-05 11:27:57,686 [WARNING ] [metricq.client      ] Failed to find version of Client: module 'metricq_grafana.client' has no attribute '__version__'
Mai 05 11:28:24 metricq metricq-grafana[118045]: 2021-05-05 11:28:24,417 [ERROR   ] [aiohttp.server      ] Error handling request
Mai 05 11:28:24 metricq metricq-grafana[118045]: Traceback (most recent call last):
Mai 05 11:28:24 metricq metricq-grafana[118045]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
Mai 05 11:28:24 metricq metricq-grafana[118045]:     resp = await self._request_handler(request)
Mai 05 11:28:24 metricq metricq-grafana[118045]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
Mai 05 11:28:24 metricq metricq-grafana[118045]:     resp = await handler(request)
Mai 05 11:28:24 metricq metricq-grafana[118045]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/views.py", line 25, in query
Mai 05 11:28:24 metricq metricq-grafana[118045]:     resp = await get_history_data(request.app, req_json)
Mai 05 11:28:24 metricq metricq-grafana[118045]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/amqp.py", line 44, in get_history_data
Mai 05 11:28:24 metricq metricq-grafana[118045]:     results = await asyncio.gather(
Mai 05 11:28:24 metricq metricq-grafana[118045]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/target.py", line 53, in get_response
Mai 05 11:28:24 metricq metricq-grafana[118045]:     return self._convert_response(data, time_delta_ns, metadata)
Mai 05 11:28:24 metricq metricq-grafana[118045]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/target.py", line 104, in _convert_response
Mai 05 11:28:24 metricq metricq-grafana[118045]:     return [
Mai 05 11:28:24 metricq metricq-grafana[118045]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/target.py", line 111, in <listcomp>
Mai 05 11:28:24 metricq metricq-grafana[118045]:     "datapoints": [
Mai 05 11:28:24 metricq metricq-grafana[118045]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/target.py", line 111, in <listcomp>
Mai 05 11:28:24 metricq metricq-grafana[118045]:     "datapoints": [
Mai 05 11:28:24 metricq metricq-grafana[118045]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/target.py", line 119, in _transform_data
Mai 05 11:28:24 metricq metricq-grafana[118045]:     for timestamp, value in function.transform_data(response):
Mai 05 11:28:24 metricq metricq-grafana[118045]:   File "/opt/metricq-grafana/lib/python3.9/site-packages/metricq_grafana/functions.py", line 208, in transform_data
Mai 05 11:28:24 metricq metricq-grafana[118045]:     ma_active_time += response_aggregates[ma_end_index].active_time * scale
Mai 05 11:28:24 metricq metricq-grafana[118045]: TypeError: unsupported operand type(s) for +=: 'int' and 'Timedelta'
```

**Comment by tilsche** [comment]
Old version with metricq 2.0...
