### ISSUE TITLE
Exception loop when responding to outdated requests

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-grafana#6]
```
Jan 24 15:56:32 igel metricq-grafana[10823]: 2019-01-24 15:56:32,257 [INFO    ] [metricq.history_client] received message from None, correlation id: mq-history-py-history-grafana-5c9b89dbc95
Jan 24 15:56:32 igel metricq-grafana[10823]: asyncio.futures.InvalidStateError: CANCELLED: <Future cancelled created at /home/service/metricq/python/metricq/history_client.py:95>
Jan 24 15:56:32 igel metricq-grafana[10823]:     raise InvalidStateError('{}: {!r}'.format(self._state, self))
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/usr/lib/python3.5/asyncio/futures.py", line 348, in set_result
Jan 24 15:56:32 igel metricq-grafana[10823]:     future.set_result(history_response)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/metricq/python/metricq/history_client.py", line 140, in _on_history_response
Jan 24 15:56:32 igel metricq-grafana[10823]:     return self.gen.send(value)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/usr/lib/python3.5/asyncio/coroutines.py", line 125, in send
Jan 24 15:56:32 igel metricq-grafana[10823]:     result = coro.send(None)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
Jan 24 15:56:32 igel metricq-grafana[10823]: Traceback (most recent call last):
Jan 24 15:56:32 igel metricq-grafana[10823]:     create_task(loop=self.loop)(callback(message))
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/aio_pika/queue.py", line 210, in consumer
Jan 24 15:56:32 igel metricq-grafana[10823]:     header_frame.properties, body)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/aio_pika/pika/channel.py", line 983, in _on_deliver
Jan 24 15:56:32 igel metricq-grafana[10823]:     self._on_deliver(*response)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/aio_pika/pika/channel.py", line 896, in _handle_content_frame
Jan 24 15:56:32 igel metricq-grafana[10823]:     return self._channels[value.channel_number]._handle_content_frame(value)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/aio_pika/pika/connection.py", line 1028, in _deliver_frame_to_channel
Jan 24 15:56:32 igel metricq-grafana[10823]:     self._deliver_frame_to_channel(frame_value)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/aio_pika/pika/connection.py", line 1427, in _process_frame
Jan 24 15:56:32 igel metricq-grafana[10823]:     self._process_frame(frame_value)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/aio_pika/pika/connection.py", line 1347, in _on_data_available
Jan 24 15:56:32 igel metricq-grafana[10823]:     self._on_data_available(data)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/aio_pika/pika/adapters/base_connection.py", line 415, in _handle_read
Jan 24 15:56:32 igel metricq-grafana[10823]:     self._handle_read()
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/aio_pika/pika/adapters/base_connection.py", line 364, in _handle_events
Jan 24 15:56:32 igel metricq-grafana[10823]:     self._callback(*self._args)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
Jan 24 15:56:32 igel metricq-grafana[10823]:     handle._run()
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 1416, in _run_once
Jan 24 15:56:32 igel metricq-grafana[10823]:     self._run_once()
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
Jan 24 15:56:32 igel metricq-grafana[10823]:     loop.run_forever()
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/aiohttp-3.3.0-py3.5-linux-x86_64.egg/aiohttp/web.py", line 120, in run_app
Jan 24 15:56:32 igel metricq-grafana[10823]:     web.run_app(app, port=4000)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/metricq-grafana/metricq_grafana/main.py", line 77, in runserver_cmd
Jan 24 15:56:32 igel metricq-grafana[10823]:     return callback(*args, **kwargs)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
Jan 24 15:56:32 igel metricq-grafana[10823]:     return ctx.invoke(self.callback, **ctx.params)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
Jan 24 15:56:32 igel metricq-grafana[10823]:     rv = self.invoke(ctx)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/click/core.py", line 697, in main
Jan 24 15:56:32 igel metricq-grafana[10823]:     return self.main(*args, **kwargs)
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
Jan 24 15:56:32 igel metricq-grafana[10823]:     load_entry_point('metricq-grafana', 'console_scripts', 'metricq-grafana')()
Jan 24 15:56:32 igel metricq-grafana[10823]:   File "/home/service/http-venv/bin/metricq-grafana", line 11, in <module>
Jan 24 15:56:32 igel metricq-grafana[10823]: source_traceback: Object created at (most recent call last):
Jan 24 15:56:32 igel metricq-grafana[10823]: future: <Task finished coro=<HistoryClient._on_history_response() done, defined at /home/service/metricq/python/metricq/history_client.py:121> ex
Jan 24 15:56:32 igel metricq-grafana[10823]: 2019-01-24 15:56:32,256 [ERROR   ] [asyncio             ] Task exception was never retrieved

```

Log full quickly, grafana's queue shows 150 delivered / s.

**Comment by kinnarr** [comment]
Should be fixed by metricq/metricq@6b1a5eb

**Comment by bmario** [comment]
Haven't seen in a while. Clsoing it.
